name: kinfraglib
channels:
  - rdkit
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - rdkit 
  - biopandas
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - bravado
  - nodejs
  - ijson
  - chembl_webresource_client
